### ISSUE TITLE
Add extra loggers, bug in variables.tf

### ISSUE THREAD

**Issue by a1k0u** [tradeparadigm/terraform-aws-ecr-repo-lambda#2]
Hi! I found small bug in `variables.tf`. There is [no closing bracket](https://github.com/tradeparadigm/terraform-aws-ecr-repo-lambda/blob/main/variables.tf#L63-L64) (`]`) for array of rules. That's why this json is not parsable and default value does not work, lifecycle does not apply to repository.

Is it really [necessary to set](https://github.com/tradeparadigm/terraform-aws-ecr-repo-lambda/blob/main/variables.tf#L67) `nullable = false` for `repo_lifecycle_policy`? You set `optional=True` [in handler](https://github.com/tradeparadigm/terraform-aws-ecr-repo-lambda/blob/main/files/create-ecr-repo/src/handler.py#L32) `lifecycle_policy()`, there is some conflict.

I think it can be difficult to [debug unparsable data](https://github.com/tradeparadigm/terraform-aws-ecr-repo-lambda/blob/main/files/create-ecr-repo/src/handler.py#L35). Maybe add `logger.warning(...)` in `lifecycle_policy()` function for case, when we unable to parse? The same can be added in all place, where we use `json.loads()`.

I will able to make a pull request with changes:
- add extra loggers for json.loads error;
- delete default value for `repo_lifecycle_policy` or fix it.

I wanna know your thoughts about changes.

**Comment by anapsix** [comment]
Apologies @a1k0u! I have not noticed this issue until you've pinged me by name on #3.
I've added the changes you've suggested to the https://github.com/tradeparadigm/terraform-aws-ecr-repo-lambda/pull/4.
Feel free to comment inline.

**Comment by a1k0u** [comment]
Thanks! I think this issue can be closed after your PR is merged.
