### ISSUE TITLE
Default lambda timeout is too short

### ISSUE THREAD

**Issue by gavinclarkeuk** [tradeparadigm/terraform-aws-ecr-repo-lambda#7]
We're seeing lambda's created with this module timing out after 3s (which is the default timeout for the terraform resource). The timeout should be extended or made configurable

**Comment by pdonorio** [comment]
Thank you so much @gavinclarkeuk - here's the new release:
https://github.com/tradeparadigm/terraform-aws-ecr-repo-lambda/releases/tag/v0.3.1

**Comment by anapsix** [comment]
@pdonorio , it would be nice to update the [CHANGELOG](https://github.com/tradeparadigm/terraform-aws-ecr-repo-lambda/blob/main/CHANGELOG.md#unreleased) accordingly 😉

**Comment by pdonorio** [comment]
> @pdonorio , it would be nice to update the [CHANGELOG](https://github.com/tradeparadigm/terraform-aws-ecr-repo-lambda/blob/main/CHANGELOG.md#unreleased) accordingly 😉

@anapsix updated :)
